stages: 
- mavenbuild
- maventest
- mavenDeploy
- androidbuild
- androidtest

maven-build:
  stage: mavenbuild
  tags: 
    - springboot_tag
  script: 
    - cd Backend/groKart_v3
    - mvn package
  only: 
    refs: 
      - main 
    changes: 
      - Backend/groKart_v3/**/* etc etc

maven-test: 
  stage: maventest
  tags: 
    - springboot_tag
  script: 
    - cd Backend/groKart_v3
    - mvn test
  artifacts: 
    paths: 
      - Backend/groKart_v3/target/*.jar 
  only: 
    refs: 
      - main 
    changes: 
      - Backend/groKart_v3/**/* etc etc

autoDeploy:
  stage: mavenDeploy
  tags:
    - springboot_tag
  script:
    - cd Backend/groKart_v3
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only: 
    refs: 
      - main 
    changes: 
      - Backend/groKart_v3/**/* etc etc

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/grokart
  tags: 
    - android_tag
  script: 
    - cd Frontend/grokart/
    - ./gradlew build
  artifacts: 
   paths: 
   - Android_test/app/build/outputs

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/grokart/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend/grokart/
    - ./gradlew test
